### ISSUE TITLE
Incorrect virus detection

### ISSUE THREAD

**Issue by isvicy** [hack-ink/AiR#109]
![image](https://github.com/user-attachments/assets/abb5893f-7cd2-4c57-8b7d-aa721cf2fcfe)

i am using windows 11 with windows defender runing, after downlading the zip for windows in the [mosh recent release](https://github.com/hack-ink/AiR/releases/tag/v0.4.6), the windows defender delete it from my machine, and reports Virus detected.

detail from windows defender is as following:
![image](https://github.com/user-attachments/assets/baaa5b4b-a8e3-4cd4-9f96-ef21dcb8b832)

i don't know if this is a false positive of  windows defender or does something unexpected is inside the zip.

**Comment by AurevoirXavier** [comment]
I think the reason is the same as on macOS. Code and packaging CI are open-sourced, there isn't virus. Let me do research on tonight and see if there is a way to sign this App on Windows.

**Comment by Barafu** [comment]
Yeah, there is. You pay money for a certificate, and Defender immediately stops seeing malwares everywhere in your code. It is a classic extortion racket.

**Comment by AurevoirXavier** [comment]
If the repository reaches over 1,000 stars (which indicates that AiR has gained more users), I will consider purchasing a certificate.

Before that, I will document this in #105 and do my best to follow the guidelines at https://learn.microsoft.com/zh-cn/defender-xdr/submission-guide to submit every version of AiR to Microsoft.

**Comment by AurevoirXavier** [comment]
https://www.microsoft.com/en-us/wdsi/submission/6e8596e8-54f1-47ff-b627-111b4de857a8

<img width="1385" alt="image" src="https://github.com/user-attachments/assets/05079770-caff-4531-8775-adc7af376292">

@isvicy Could you try again?

**Comment by AurevoirXavier** [comment]
Tested successfully on my Windows 11. Please reopen if the issue can be reproduced.
