### ISSUE TITLE
Couldn't find the icon to reopen the program on Windows

### ISSUE THREAD

**Issue by fulyaec** [hack-ink/AiR#88]
I downloaded the binary executable version 0.4.2 on Windows. After running the program, I minimized the window, and then I couldn't find the icon anymore. I am unable to reopen the program window.

**Comment by AurevoirXavier** [comment]
> I downloaded the binary executable version 0.4.2 on Windows. After running the program, I minimized the window, and then I couldn't find the icon anymore. I am unable to reopen the program window.

Thanks, I'll look into this later today.

**Comment by AurevoirXavier** [comment]
https://github.com/hack-ink/AiR/commit/b658c238b209f9b72eccd408a293b915fad5e33a
